### ISSUE TITLE
Can't use other props when cellContentView is used

### ISSUE THREAD

**Issue by MarcoLeti** [Purii/react-native-tableview-simple#707]
Hi,

not so sure if this is an issue or expected behaviour but cellContentView is listed under the props but it seems it cannot be used together with other props (for example title). The title must be rendere in a Text tag inside the cellContentView. But other props like for example highlightUnderlayColor can't be used when cellContentView is.

Could you please provide me guidelines how to proceed?

Thanks

**Comment by Purii** [comment]
Hi @MarcoLeti !

Yep. That's correct. The `title` is part of the ContentView Container.
If you replace the whole Container via `cellContentView` there's no place render the title anymore. `cellContentView` is meant to be used if you want maximum flexibility. See more here: https://github.com/Purii/react-native-tableview-simple/blob/50c6e83401a56e0a18c58277b332703a89522851/src/components/Cell.tsx#L379

`highlightUnderlayColor` should be usable because it's on the layer above. Can you create an example please?

I want to update the types so it becomes clearer but couldn't find the time. Would highly appreciate a PR for that.

Patrick
